function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.6 and Automated Driving Toolbox 2.0.
% Generated on: 03-Jun-2020 18:37:46

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [40 10.1 0;
    18.2 9.9 0;
    -1.8 11.1 0];
road(scenario, roadCenters);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [3.7 10.8 0]);
waypoints = [3.7 10.8 0;
    20.5 9.5 0;
    33.9 9.8 0;
    45.9 9.9 0];
speed = 30;
trajectory(egoVehicle, waypoints, speed);

